<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en" sourcelanguage="fi">
<context>
    <name>about_description</name>
    <message>
        <location filename="mainwindow.py" line="89"/>
        <source>Yksinkertainen sovellus ilmatieteenlaitoksen säähavaintodatan lataamiseen.
Jos ohjelma lakkaa toimimasta, voit ottaa yhteyttä

Tuomas Salmi, 2015
https://github.com/Tumetsu/Ilmatieteenlaitoksen-saadata-lataaja
salmi.tuomas@gmail.com</source>
        <translation>A simple application to download data from Finnish Meteorological Institute&apos;s open data service. 
In case there is problems, you can contact 

Tuomas Salmi, 2015
https://github.com/Tumetsu/Ilmatieteenlaitoksen-saadata-lataaja
salmi.tuomas@gmail.com</translation>
    </message>
</context>
<context>
    <name>aboutheading</name>
    <message>
        <location filename="mainwindow.py" line="89"/>
        <source>Tietoa</source>
        <translation>About</translation>
    </message>
</context>
<context>
    <name>datenotfound_error</name>
    <message>
        <location filename="messages.py" line="9"/>
        <source>Määritettyä ajanjaksoa ei löytynyt.
Todennäköisesti ilmatieteenlaitoksella ei ole dataa tälle ajanjaksolle.
Kokeile pitempää ajanjaksoa, esim. yhtä vuotta tai myöhäisempää aloituspäivämäärää.

Virheen kuvaus:
</source>
        <translation>Specified date and time could not be found.
Most likely FMI doesn&apos;t have data for this time-period.
Please try longer time-span,for example one year or later beginning date.

Error details:  </translation>
    </message>
</context>
<context>
    <name>downloading_weatherdata</name>
    <message>
        <location filename="downloadProgress.py" line="32"/>
        <source>Ladataan säädataa...</source>
        <translation>Downloading weatherdata...</translation>
    </message>
</context>
<context>
    <name>enddate_warning</name>
    <message>
        <location filename="messages.py" line="13"/>
        <source>Lopetus päivämäärä ei saa edeltää aloitus päivämäärää</source>
        <translation>Ending date is not allowed to predate the beginning date.</translation>
    </message>
</context>
<context>
    <name>requestfailed_error</name>
    <message>
        <location filename="downloadProgress.py" line="68"/>
        <source>Datapyyntö ei onnistunut.
Oletko asettanut vaadittavan tunnisteavaimen tai onko se virheellinen?

Ilmatieteenlaitos vaatii rekisteröitymistä palveluun ennen sen käyttöä. Katso lisätietoa valikosta Tiedosto-&gt;Aseta tunnisteavain.</source>
        <translation>Datarequest failed.
Have you set the required API-key or is it invalid?

FMI requires users to register into their service before using it. More information in File-&gt;Set API-key.</translation>
    </message>
</context>
<context>
    <name>save_weather_data</name>
    <message>
        <location filename="mainwindow.py" line="174"/>
        <source>Tallenna säädata csv-muodossa:</source>
        <translation>Save weatherdata in csv-format:</translation>
    </message>
</context>
<context>
    <name>setapikeyheading</name>
    <message>
        <location filename="mainwindow.py" line="94"/>
        <source>Aseta tunnisteavain</source>
        <translation>Set API-key</translation>
    </message>
</context>
<context>
    <name>setapikeyinstruction</name>
    <message>
        <location filename="mainwindow.py" line="94"/>
        <source>Käyttääksesi sovellusta tarvitset ilmatieteenlaitoksen avoimen datan tunnisteavaimen.
Mene osoitteeseen http://ilmatieteenlaitos.fi/avoin-data saadaksesi lisätietoa avaimen hankkimisesta.

Kun olet rekisteröitynyt ja saanut tekstimuotoisen tunnisteavaimen, kopioi se tähän:</source>
        <translation>To use this application you&apos;ll need FMI&apos;s API-key. Go to the  http://ilmatieteenlaitos.fi/avoin-data to get more infromation about obtaining the API-key.

After you have registered to the FMI&apos;s service, copy and paste the API-key into field below:</translation>
    </message>
</context>
<context>
    <name>setapikeymessage</name>
    <message>
        <location filename="mainwindow.py" line="25"/>
        <source>Tunnisteavainta ei ole maaritetty. Aseta se valikossa Tiedosto-&gt;Aseta tunnisteavain</source>
        <translation>API-key is not defined. Set it in File-&gt;Set API-key</translation>
    </message>
</context>
<context>
    <name>startenddate_warning</name>
    <message>
        <location filename="messages.py" line="16"/>
        <source>Aloitus ja lopetuspäivämäärät eivät saa olla samoja</source>
        <translation>Beinning and ending dates can&apos;t be the same date</translation>
    </message>
</context>
<context>
    <name>unknown_error</name>
    <message>
        <location filename="messages.py" line="6"/>
        <source>Tuntematon virhe: </source>
        <translation>Unknown error: </translation>
    </message>
</context>
<context>
    <name>weatherstationnotfound_error</name>
    <message>
        <location filename="downloadProgress.py" line="64"/>
        <source>Määritettyä sääasemaa ei löydetty.
Ilmatieteenlaitoksen palvelussa on häiriö tai mikäli ongelma toistuu muillakin kohteilla, saattaa tämä ohjelma vaatia päivitystä. Katso tiedot yhteydenotosta Tiedosto-&gt;Tietoa valikosta.

Virheen kuvaus:
</source>
        <translation>Weather station was not found.
There might be a problem with FMI&apos;s service. If problem appears with other stations, software might require updating. You can check contact-details from File-&gt;About

Error description: </translation>
    </message>
</context>
</TS>
