<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en" sourcelanguage="fi">
<context>
    <name>about_description</name>
    <message>
        <location filename="mainwindow.py" line="92"/>
        <source>Yksinkertainen sovellus ilmatieteenlaitoksen säähavaintodatan lataamiseen.
Jos ohjelma lakkaa toimimasta, voit ottaa yhteyttä

Tuomas Salmi, 2015
https://github.com/Tumetsu/Ilmatieteenlaitoksen-saadata-lataaja
salmi.tuomas@gmail.com</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>aboutheading</name>
    <message>
        <location filename="mainwindow.py" line="92"/>
        <source>Tietoa</source>
        <translation type="unfinished">About</translation>
    </message>
</context>
<context>
    <name>datenotfound_error</name>
    <message>
        <location filename="mainwindow.py" line="17"/>
        <source>Määritettyä ajanjaksoa ei löytynyt.
Todennäköisesti ilmatieteenlaitoksella ei ole dataa tälle ajanjaksolle.
Kokeile pitempää ajanjaksoa, esim. yhtä vuotta tai myöhäisempää aloituspäivämäärää.

Virheen kuvaus:
</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>downloading_weatherdata</name>
    <message>
        <location filename="downloadProgress.py" line="32"/>
        <source>Ladataan säädataa...</source>
        <translation>Downloading weatherdata...</translation>
    </message>
</context>
<context>
    <name>enddate_warning</name>
    <message>
        <location filename="mainwindow.py" line="16"/>
        <source>Lopetus päivämäärä ei saa edeltää aloitus päivämäärää</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>requestfailed_error</name>
    <message>
        <location filename="downloadProgress.py" line="68"/>
        <source>Datapyyntö ei onnistunut.
Oletko asettanut vaadittavan tunnisteavaimen tai onko se virheellinen?

Ilmatieteenlaitos vaatii rekisteröitymistä palveluun ennen sen käyttöä. Katso lisätietoa valikosta Tiedosto-&gt;Aseta tunnisteavain.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>save_weather_data</name>
    <message>
        <location filename="mainwindow.py" line="177"/>
        <source>Tallenna säädata csv-muodossa:</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>setapikeyheading</name>
    <message>
        <location filename="mainwindow.py" line="97"/>
        <source>Aseta tunnisteavain</source>
        <translation>Set API-key</translation>
    </message>
</context>
<context>
    <name>setapikeyinstruction</name>
    <message>
        <location filename="mainwindow.py" line="97"/>
        <source>Käyttääksesi sovellusta tarvitset ilmatieteenlaitoksen avoimen datan tunnisteavaimen.
Mene osoitteeseen http://ilmatieteenlaitos.fi/avoin-data saadaksesi lisätietoa avaimen hankkimisesta.

Kun olet rekisteröitynyt ja saanut tekstimuotoisen tunnisteavaimen, kopioi se tähän:</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>setapikeymessage</name>
    <message>
        <location filename="mainwindow.py" line="28"/>
        <source>Tunnisteavainta ei ole maaritetty. Aseta se valikossa Tiedosto-&gt;Aseta tunnisteavain</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>startenddate_warning</name>
    <message>
        <location filename="mainwindow.py" line="15"/>
        <source>Aloitus ja lopetuspäivämäärät eivät saa olla samoja</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>unknown_error</name>
    <message>
        <location filename="mainwindow.py" line="19"/>
        <source>Tuntematon virhe: </source>
        <translation>Unknown error: </translation>
    </message>
</context>
<context>
    <name>weatherstationnotfound_error</name>
    <message>
        <location filename="downloadProgress.py" line="64"/>
        <source>Määritettyä sääasemaa ei löydetty.
Ilmatieteenlaitoksen palvelussa on häiriö tai mikäli ongelma toistuu muillakin kohteilla, saattaa tämä ohjelma vaatia päivitystä. Katso tiedot yhteydenotosta Tiedosto-&gt;Tietoa valikosta.

Virheen kuvaus:
</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
